"""Peachtree Roofing & Exteriors — company profile (Metro Atlanta, Georgia).

All brand-, geo-, and market-specific data for this company. Shared pipeline
code reads these via blog_automation.company.get_profile().
"""

from __future__ import annotations

# --- Identity ---
COMPANY_NAME = "Peachtree Roofing & Exteriors"
COMPANY_SHORT = "Peachtree"
METRO_AREA = "Metro Atlanta"
STATE = "Georgia"

# --- Writing / branding (write_common.py, post.py, draft_scorer.py, ...) ---
AUTHOR_CREDENTIALS = "Licensed Roofing Contractor, Metro Atlanta"
CTA_SENTENCE = "Contact Peachtree Roofing & Exteriors for a free inspection."
BYLINE_SERVICE_SENTENCE = "Peachtree Roofing & Exteriors serves homeowners across Metro Atlanta."
# Possessive brand name used in "... write from <name>'s contractor perspective."
CONTRACTOR_PERSPECTIVE_NAME = "Peachtree Roofing"

METRO_LOCATIONS = [
    "Atlanta",
    "Alpharetta",
    "Brookhaven",
    "Buckhead",
    "Chamblee",
    "Cherokee",
    "Cobb",
    "Conyers",
    "Decatur",
    "DeKalb",
    "Duluth",
    "Dunwoody",
    "East Cobb",
    "Fayette County",
    "Fulton",
    "Gwinnett",
    "Henry",
    "Johns Creek",
    "Kennesaw",
    "Lawrenceville",
    "Lithonia",
    "Marietta",
    "Midtown",
    "Norcross",
    "Peachtree City",
    "Roswell",
    "Sandy Springs",
    "Smyrna",
    "Stone Mountain",
    "Suwanee",
    "Tucker",
    "Vinings",
    "Woodstock",
]

# Ordered substring-marker → display name for source_display_name().
OUTLET_NAME_BY_DOMAIN_MARKER: dict[str, str] = {
    "fox5atlanta": "FOX 5 Atlanta",
    "11alive": "11Alive",
    "wsbtv": "WSB-TV",
    "ajc": "AJC",
    "weather.gov": "NWS Atlanta",
    "legis.ga.gov": "Georgia General Assembly",
}

# --- Posting (post.py) ---
DEFAULT_TAGS = ["Metro Atlanta", "Georgia"]
DEFAULT_KEYWORDS = [
    "Metro Atlanta roofing",
    "Georgia homeowners",
    "roofing contractor Atlanta",
    "roof replacement Atlanta GA",
    "storm damage roof repair Georgia",
]

# --- Prompt template variables ({{key}} placeholders in prompts/*.txt; see blog_automation.company.render_template) ---
PROMPT_VARS: dict[str, str] = {'byline_service_sentence': 'Peachtree Roofing & Exteriors serves homeowners across Metro Atlanta.',
 'claims_assistance_phrase': 'insurance claims assistance',
 'company_name': 'Peachtree Roofing & Exteriors',
 'company_profile_block': 'COMPANY PROFILE — weave these facts naturally into the post where the topic '
                          'fits:\n'
                          '- **Name:** Peachtree Roofing & Exteriors (also Peachtree Restorations) — serving '
                          'Metro Atlanta since 2012; 8,000+ customers served\n'
                          '- **Certifications:** GAF Master Elite® (top 3% of U.S. roofers) | CertainTeed '
                          'Select ShingleMaster™\n'
                          '- **Flagship technology:** AI-powered drone roof inspection with comprehensive '
                          'photo-documented report\n'
                          '- **Services:** full roof replacement (residential and commercial), storm damage '
                          'restoration, insurance claims assistance, seamless gutters (paired with roof '
                          'replacement)\n'
                          '- **Financing:** Wells Fargo financing available; manufacturer warranties from '
                          'GAF and CertainTeed\n'
                          '\n'
                          'WHEN TO MENTION PEACHTREE IN THE BODY (1–2 sentences per touchpoint, varied '
                          'phrasing each time):\n'
                          '- **Inspection sections** → reference the AI-powered drone inspection and '
                          'photo-documented report\n'
                          '- **Materials / replacement sections** → reference GAF Master Elite certification '
                          'or CertainTeed Select ShingleMaster and manufacturer warranties\n'
                          "- **Insurance / claims sections** → reference Peachtree's insurance claims "
                          'assistance experience\n'
                          '- **Cost sections** → reference Wells Fargo financing options\n'
                          '\n'
                          'Do NOT use the exact phrase "Contact Peachtree Roofing & Exteriors for a free '
                          'inspection." in these mid-body mentions — reserve that phrase for the single '
                          'closing CTA only.\n'
                          '\n'
                          'KEYWORD TARGETS — use these naturally; do not repeat or force them:\n'
                          '- "roof inspection" or "professional roof inspection" — at least twice in the '
                          'post\n'
                          '- "AI drone inspection" or "AI-powered drone inspection" — at least once when '
                          'inspection is discussed\n'
                          '- "storm damage restoration" — when the story angle involves storm damage\n'
                          '- "roof replacement" (full phrase) — at least twice\n'
                          '- "insurance claims" — when the angle covers claims or coverage\n'
                          '- "GAF Master Elite" or "CertainTeed" — at least once when discussing materials '
                          'or contractor selection\n'
                          '\n'
                          'GEO KEYWORD BANK — pick 4-8 phrases below that fit the topic and weave them in '
                          'naturally; never force a phrase where it breaks sentence flow, and never repeat '
                          'the same exact phrase more than twice in one post:\n'
                          '- Service: "storm damage roof repair", "hail damage roof repair", "emergency roof '
                          'repair", "new roof installation", "flat roof repair", "metal roofing", "siding '
                          'installation", "exterior renovation", "gutter installation", "fascia and soffit '
                          'repair", "window replacement"\n'
                          '- Local-contractor pattern: when naming a covered suburb (Alpharetta, Marietta, '
                          'Roswell, Woodstock, Kennesaw, Cumming, Milton, Dunwoody, Sandy Springs, Johns '
                          'Creek, Buckhead, East Cobb, Peachtree City), pair at least one mention with '
                          '"roofing contractor" or "roofing company" phrasing (e.g., "a roofing contractor '
                          'in Alpharetta, GA")\n'
                          '- Informational: "how much does a new roof cost in Georgia", "signs you need a '
                          'new roof", "how long does a roof last in Georgia", "best roofing materials for '
                          'Georgia climate", "when to repair vs. replace a roof", "how to choose a roofing '
                          'contractor in Atlanta", "energy efficient roofing", "roof ventilation tips", '
                          '"impact resistant roofing"\n'
                          '- Trust: "GAF certified roofing contractor", "licensed and insured roofing '
                          'contractor", "free roof inspection"',
 'company_short': 'Peachtree',
 'contractor_perspective_name': 'Peachtree Roofing',
 'county_guides_counties': 'Fulton, DeKalb, Cobb, Gwinnett, Cherokee, and nearby areas',
 'cta_sentence': 'Contact Peachtree Roofing & Exteriors for a free inspection.',
 'drone_inspection_phrase': 'AI-powered drone inspection',
 'drone_inspection_phrase_plural': 'AI-powered drone inspections',
 'example_county_a': 'Gwinnett County',
 'example_county_b': 'Cobb County',
 'example_h2_older_roofs': 'What Does Flash Flood Risk Mean for Older Roofs in Fulton County?',
 'example_h2_risk': 'Which Gwinnett County Neighborhoods Face the Highest Flash Flood Risk?',
 'example_h2_risk_scenario': 'Which Gwinnett County Neighborhoods Face the Highest Flash Flood and Roof Leak '
                             'Risk?',
 'example_neighborhoods': 'Old Fourth Ward, Morningside',
 'example_outlets': 'FOX 5 Atlanta, WSB-TV, AJC, 11Alive, NWS, Georgia General Assembly',
 'example_townhome_row': 'Marietta townhomes — 1980s/90s builds',
 'example_two_counties': 'Cobb and Cherokee counties',
 'example_two_counties_industry': 'Gwinnett and Cobb County homeowners',
 'example_vignette_homeowner': 'Marietta homeowner',
 'example_vignette_homeowner_2': 'homeowner in Decatur',
 'example_vignette_name_city': 'Marcus in Marietta',
 'example_vignette_name_city_2': 'Denise in Decatur',
 'housing_stock_examples': '1970s–90s ranch homes, postwar frame construction, 1990s suburban tract builds',
 'insurance_bill': 'HB511',
 'insurance_cluster_key': 'ga_insurance_navigation',
 'mention_cost_services': 'storm damage restoration, Wells Fargo financing, or insurance claims assistance',
 'mention_example_certification': '(e.g., "As a GAF Master Elite certified contractor based in Roswell, '
                                  'Peachtree Roofing & Exteriors has completed storm damage assessments '
                                  'across Gwinnett, Cobb, Fulton, and Cherokee counties.")',
 'mention_example_inspection': '(e.g., "Peachtree Roofing & Exteriors uses AI-powered drone inspections to '
                               'document storm damage before the insurance adjuster visits — a '
                               'photo-documented report that strengthens your claim from day one.")',
 'metro_area': 'Metro Atlanta',
 'metro_city': 'Atlanta',
 'out_of_state_bill_examples': '"California Senate passes...", "Colorado Governor signs...", "Texas '
                               'legislature approves...", "Florida insurance reform..."',
 'out_of_state_examples_audit': 'Michigan, Texas, California',
 'out_of_state_examples_events': 'Colorado insurance law, California wildfire policy, Texas storm response',
 'out_of_state_examples_paren': 'Colorado, California, Texas, New York, Florida',
 'out_of_state_list_a': 'California, Colorado, Texas, Florida, New York, or any other state',
 'out_of_state_list_b': 'California, Colorado, Texas, Florida, or any other non-Georgia state',
 'state': 'Georgia',
 'storm_season_anchor_phrase': "Metro Atlanta's April–September storm season",
 'storm_season_phrase': "Atlanta's April–September storm season peak",
 'us_region_phrase': 'the Southeast or Sun Belt'}

# --- Strategy cluster keys ---
INSURANCE_CLUSTER_KEY = "ga_insurance_navigation"

# --- Search (pipeline/search.py) ---
SEARCH_TRADE_STAGE_NAME = "georgia_roofing_trade_21_day"

SEARCH_PRIORITY_SOURCES = ['fox5atlanta.com',
 'wsbtv.com',
 'ajc.com',
 '11alive.com',
 'weather.gov',
 'legis.ga.gov',
 'dca.ga.gov',
 'wsbradio.com',
 'wxia.com',
 'wgcl.com',
 'atlanta.curbed.com',
 'patch.com',
 'atlantabusinesschronicle.com']

SEARCH_SECONDARY_SOURCES = ['cbs46.com',
 'atlantan.com',
 'mdjonline.com',
 'gwinnettdailypost.com',
 'rockdalenewtoncitizen.com',
 'accesswdun.com',
 'reporternewspapers.net',
 'northside-neighbor.com',
 'neighbornewspapers.com',
 'cherokeetribune.com',
 'henryherald.com',
 'claytoncrescent.com',
 'newnan-times-herald.com',
 'douglascountysentinel.com',
 'payson roundup.com',
 'forsythnews.com',
 'alpharettatn.com',
 'roswellmagazine.com',
 'mariettadailyjournal.com',
 'smyrnaobserver.com',
 'tuscaloosanews.com']

SEARCH_OFFICIAL_SOURCES = ['weather.gov',
 'legis.ga.gov',
 'dca.ga.gov',
 'oci.georgia.gov',
 'atlantaga.gov',
 'fultoncountyga.gov',
 'dekalbcountyga.gov',
 'cobbcounty.org',
 'gwinnettcounty.com',
 'cherokeega.com',
 'fema.gov',
 'henrycountyga.gov',
 'claytoncountyga.gov',
 'douglascountyga.gov',
 'paulding.gov',
 'forsythco.com',
 'nws.noaa.gov',
 'spc.noaa.gov',
 'ready.gov',
 'insurance.georgia.gov',
 'dol.georgia.gov',
 'georgiabuilds.com',
 'icc-es.org']

SEARCH_ROOFING_TRADE_SOURCES = ['insurancejournal.com',
 'ajc.com',
 'atlantabusinesschronicle.com',
 'fox5atlanta.com',
 '11alive.com',
 'wsbtv.com',
 'wsbradio.com',
 'insurance.georgia.gov',
 'oci.georgia.gov',
 'roughnotes.com',
 'propertycasualty360.com',
 'mariettadailyjournal.com',
 'gwinnettdailypost.com',
 'forsythnews.com']

SEARCH_STRATEGY_CLUSTERS = {'storm_damage': {'pillar_topic': 'Metro Atlanta storm damage inspection and repair',
                  'trigger_window_hours': 72,
                  'queries': ['Atlanta hail roof damage',
                              'Gwinnett storm roof damage',
                              'Cobb County wind roof damage',
                              'DeKalb tornado roof damage',
                              'North Georgia severe weather roof',
                              'Atlanta tree fall roof damage',
                              'Fulton hail shingle damage',
                              'Cherokee hail roof replacement',
                              'Atlanta flash flood roof leak',
                              'Georgia straight line wind roof',
                              'Metro Atlanta storm roof inspection',
                              'Newton County tornado roof',
                              'Atlanta microburst roof damage']},
 'ga_insurance_navigation': {'pillar_topic': 'Georgia roof insurance claims, RCV vs ACV, HB511',
                             'trigger_window_hours': 48,
                             'queries': ['Georgia roof insurance claim',
                                         'Atlanta RCV ACV roof claim',
                                         'Georgia HB511 storm deductible',
                                         'Metro Atlanta roof insurance nonrenewal',
                                         'Georgia roof depreciation claim',
                                         'Atlanta insurance adjuster roof inspection',
                                         'Georgia roof claim supplement',
                                         'Fulton County roof insurance dispute',
                                         'Gwinnett homeowners insurance roof age',
                                         'Georgia actual cash value roof',
                                         'Atlanta roof insurance endorsement',
                                         'Georgia insurance commissioner roof claim',
                                         'Cobb County hail insurance claim',
                                         'Georgia catastrophe savings roof deductible']},
 'roof_safety': {'pillar_topic': 'Atlanta roof safety, fires, penetrations, structural risk',
                 'trigger_window_hours': 48,
                 'queries': ['Atlanta roof fire damage',
                             'DeKalb chimney roof fire',
                             'Cobb unsafe structure roof',
                             'Gwinnett pipe boot roof leak',
                             'Atlanta attic mold roof ventilation',
                             'Fulton building code roof inspection',
                             'Georgia roof collapse structural',
                             'Atlanta HVAC roof penetration fire',
                             'Metro Atlanta flat roof ponding',
                             'Cherokee ice dam roof damage',
                             'Atlanta solar panel roof leak',
                             'Henry County roof structural inspection',
                             'Atlanta flashing failure roof leak',
                             'Georgia roof ventilation fire safety',
                             'Clayton roof water intrusion damage']},
 'county_guides': {'pillar_topic': 'County-specific roof guidance for Metro Atlanta',
                   'trigger_window_hours': None,
                   'queries': ['Fulton County roof permit',
                               'DeKalb County roof storm damage',
                               'Cobb County hail roof damage',
                               'Gwinnett County roof permit',
                               'Cherokee County storm roof repair',
                               'Clayton County roof insurance claim',
                               'Henry County hail roof damage',
                               'Douglas County roof permit storm',
                               'Forsyth County roof replacement hail',
                               'Paulding County storm roof damage',
                               'Fulton County unsafe structure roof',
                               'DeKalb County roof building permit',
                               'Gwinnett hail roof insurance',
                               'Cobb County roof code inspection',
                               'Cherokee County roof permit requirements',
                               'Henry County roof storm insurance']}}

SEARCH_LOCAL_TERMS = ['atlanta',
 'metro atlanta',
 'north georgia',
 'georgia',
 'fulton',
 'dekalb',
 'cobb',
 'gwinnett',
 'clayton',
 'cherokee',
 'henry',
 'henry county',
 'buckhead',
 'marietta',
 'alpharetta',
 'dunwoody',
 'woodstock',
 'east cobb',
 'vinings',
 'chamblee',
 'sandy springs',
 'roswell',
 'decatur',
 'lawrenceville',
 'smyrna',
 'paulding',
 'forsyth',
 'bartow',
 'newton',
 'rockdale',
 'fayette',
 'fayetteville',
 'peachtree city',
 'stockbridge',
 'mcdonough',
 'canton',
 'ball ground',
 'holly springs',
 'milton',
 'johns creek',
 'norcross',
 'buford',
 'suwanee',
 'duluth',
 'kennesaw',
 'acworth',
 'powder springs',
 'douglasville',
 'lithia springs',
 'college park',
 'east point',
 'hapeville',
 'forest park',
 'jonesboro',
 'southeast']

SEARCH_STATE_LOCAL_TERMS = ['georgia', 'north georgia', 'southeast']

SEARCH_TOPIC_TERMS = ['roof',
 'roofing',
 'shingle',
 'gutter',
 'siding',
 'exterior',
 'storm',
 'hail',
 'wind',
 'thunderstorm',
 'tornado',
 'weather',
 'insurance',
 'claim',
 'building code',
 'hoa',
 'fire',
 'damage',
 'flooding',
 'permit',
 'inspection',
 'unsafe',
 'safety',
 'structural',
 'construction',
 'hvac',
 'pipe boot',
 'flashing',
 'attic',
 'ventilation',
 'deductible',
 'rcv',
 'acv',
 'hb511',
 'house bill 511',
 'architectural shingle',
 'asphalt shingle',
 'metal roof',
 'flat roof',
 'tpo',
 'epdm',
 'modified bitumen',
 'slate roof',
 'tile roof',
 'ridge cap',
 'ridge vent',
 'soffit',
 'fascia',
 'drip edge',
 'ice barrier',
 'underlayment',
 'felt paper',
 'synthetic underlayment',
 'decking',
 'roof deck',
 'plywood decking',
 'osb decking',
 'roof truss',
 'rafter',
 'skylight',
 'chimney flashing',
 'step flashing',
 'valley flashing',
 'pipe collar',
 'boot seal',
 'roof cement',
 'caulk',
 'sealant',
 'granule loss',
 'granule',
 'blistering',
 'curling shingle',
 'lifted shingle',
 'cracked shingle',
 'missing shingle',
 'moss',
 'algae',
 'staining',
 'ponding water',
 'ice dam',
 'gutter guard',
 'downspout',
 'soffit vent',
 'ridge ventilation',
 'power attic ventilator',
 'solar attic fan',
 'roofing contractor',
 'licensed roofer',
 'roofing estimate',
 'roofing warranty',
 'manufacturer warranty',
 'workmanship warranty',
 'gaf',
 'owens corning',
 'certainteed',
 'tamko',
 'atlas roofing',
 'iko',
 'emergency tarp',
 'temporary repair',
 'supplemental claim',
 'public adjuster',
 'xactimate',
 'replacement cost',
 'actual cash value',
 'depreciation',
 'recoverable depreciation',
 'non recoverable depreciation',
 'roof age',
 'roof lifespan',
 'roof inspection report',
 'drone inspection']

SEARCH_PRIMARY_CORE_ROOFING_TERMS = ['roof',
 'roofing',
 'shingle',
 'gutter',
 'siding',
 'hail',
 'wind',
 'thunderstorm',
 'tornado',
 'flashing',
 'attic',
 'underlayment',
 'roofer',
 'roofing contractor',
 'emergency tarp',
 'architectural shingle',
 'metal roof',
 'flat roof',
 'pipe boot',
 'ridge cap',
 'soffit',
 'fascia',
 'granule loss',
 'missing shingle',
 'roof leak',
 'ice dam',
 'roof collapse',
 'roof inspection report',
 'drone inspection',
 'building permit',
 'hb511',
 'house bill 511',
 'contractor',
 'restoration',
 'roof restoration',
 'milestone']

SEARCH_OUT_OF_MARKET_STATE_TERMS = ['colorado',
 'texas',
 'florida',
 'california',
 'arizona',
 'ohio',
 'alabama',
 'tennessee',
 'louisiana',
 'new york',
 'pennsylvania',
 'michigan',
 'illinois',
 'virginia',
 'maryland',
 'north carolina',
 'south carolina',
 'kentucky',
 'mississippi',
 'arkansas',
 'oklahoma',
 'missouri',
 'indiana',
 'wisconsin',
 'minnesota',
 'iowa',
 'nebraska',
 'kansas',
 'utah',
 'nevada',
 'oregon',
 'washington state',
 'new mexico',
 'connecticut',
 'massachusetts',
 'new jersey',
 'denver',
 'centennial, co',
 'boulder',
 'phoenix',
 'dallas',
 'houston',
 'miami',
 'orlando']

SEARCH_METRO_NEWS_DOMAIN_EXCLUSIONS = {'legis.ga.gov', 'weather.gov', 'dca.ga.gov'}

SEARCH_STATE_SCOPED_DOMAIN_MARKERS = ('.ga.gov',
 'georgiabuilds.com',
 'insurance.georgia.gov',
 'legis.ga.gov',
 'fox5atlanta.com',
 'atlantaga.gov',
 'atlanta.curbed.com')

SEARCH_CLUSTER_TERMS = {'storm_damage': ['roof',
                  'storm',
                  'hail',
                  'wind',
                  'thunderstorm',
                  'tornado',
                  'weather',
                  'insurance',
                  'claim',
                  'missing shingle',
                  'lifted shingle',
                  'granule loss',
                  'tree branch',
                  'emergency tarp',
                  'temporary repair',
                  'roof leak',
                  'water intrusion',
                  'ice dam',
                  'ponding water',
                  'derecho',
                  'microburst',
                  'straight line wind'],
 'ga_insurance_navigation': ['roof',
                             'insurance',
                             'claim',
                             'deductible',
                             'rcv',
                             'acv',
                             'hb511',
                             'house bill 511',
                             'policy',
                             'replacement cost',
                             'actual cash value',
                             'depreciation',
                             'recoverable depreciation',
                             'supplemental claim',
                             'public adjuster',
                             'xactimate',
                             'roof age',
                             'nonrenewal',
                             'endorsement',
                             'exclusion',
                             'catastrophe savings account',
                             'underpaid claim'],
 'roof_safety': ['roof',
                 'fire',
                 'safety',
                 'structural',
                 'construction',
                 'inspection',
                 'hvac',
                 'attic',
                 'ventilation',
                 'flashing',
                 'pipe boot',
                 'boot seal',
                 'chimney flashing',
                 'step flashing',
                 'granule loss',
                 'moss',
                 'algae',
                 'mold',
                 'moisture',
                 'rot',
                 'roof collapse',
                 'structural failure',
                 'solar panel',
                 'flat roof',
                 'ponding water',
                 'ice dam',
                 'power attic ventilator'],
 'county_guides': ['roof',
                   'permit',
                   'storm',
                   'hail',
                   'wind',
                   'insurance',
                   'replacement',
                   'repair',
                   'building permit',
                   'residential permit',
                   'permit requirements',
                   'unsafe structure',
                   'code violation',
                   'hoa requirement',
                   'county ordinance',
                   'inspection required',
                   'licensed contractor required']}

# --- Evaluate (pipeline/evaluate.py) ---
# 'generic' is filled with str.format(title=...).
EVALUATE_FALLBACK_ANGLES = {'storm': 'What should Metro Atlanta homeowners inspect after this storm or damage report?',
 'insurance': 'How does this Georgia insurance update affect roof repair or replacement '
              'claims?',
 'safety': 'What roof safety risks should Atlanta homeowners understand from this local '
           'report?',
 'generic': 'What should Atlanta homeowners know about {title}?'}
