"""TC Roofing & Restorations — company profile (Dallas-Fort Worth, Texas).

All brand-, geo-, and market-specific data for this company. Shared pipeline
code reads these via blog_automation.company.get_profile().
"""

from __future__ import annotations

# --- Identity ---
COMPANY_NAME = "TC Roofing & Restorations"
COMPANY_SHORT = "TC Roofing"
METRO_AREA = "Dallas-Fort Worth"
STATE = "Texas"

# --- Writing / branding (write_common.py, post.py, draft_scorer.py, ...) ---
AUTHOR_CREDENTIALS = "Licensed Roofing Contractor, Dallas-Fort Worth"
CTA_SENTENCE = "Contact TC Roofing & Restorations for a free inspection."
BYLINE_SERVICE_SENTENCE = "TC Roofing & Restorations serves homeowners across the Dallas-Fort Worth Metroplex."
# Possessive brand name used in "... write from <name>'s contractor perspective."
CONTRACTOR_PERSPECTIVE_NAME = "TC Roofing"

METRO_LOCATIONS = [
    "Allen",
    "Anna",
    "Arlington",
    "Bedford",
    "Burleson",
    "Carrollton",
    "Cedar Hill",
    "Collin County",
    "Dallas",
    "Dallas County",
    "Denton",
    "Denton County",
    "DeSoto",
    "Flower Mound",
    "Fort Worth",
    "Frisco",
    "Garland",
    "Grand Prairie",
    "Grapevine",
    "Irving",
    "Keller",
    "Lewisville",
    "Little Elm",
    "Mansfield",
    "McKinney",
    "Mesquite",
    "Plano",
    "Richardson",
    "Rockwall",
    "Rowlett",
    "Southlake",
    "Tarrant County",
    "Wylie",
]

# Ordered substring-marker → display name for source_display_name().
OUTLET_NAME_BY_DOMAIN_MARKER: dict[str, str] = {
    "wfaa": "WFAA",
    "nbcdfw": "NBC DFW",
    "fox4news": "Fox 4",
    "dallasnews": "Dallas Morning News",
    "star-telegram": "Fort Worth Star-Telegram",
    "cbsdfw": "CBS DFW",
    "weather.gov": "NWS Fort Worth",
    "legis.state.tx.us": "Texas Legislature",
    "tdi.texas.gov": "Texas Department of Insurance",
}

# --- Posting (post.py) ---
DEFAULT_TAGS = ["Dallas-Fort Worth", "Texas"]
DEFAULT_KEYWORDS = ["Dallas-Fort Worth roofing", "Texas homeowners"]

# --- Prompt template variables ({{key}} placeholders in prompts/*.txt; see blog_automation.company.render_template) ---
# TODO: fill in TC certifications/services/financing facts — company_profile_block and the
# mention_example_* values below were built only from claims present in the original TC repo's
# prompts (GAF Master Elite, serving DFW since 2018, AI drone inspection, storm damage
# restoration, hail damage repair, insurance claim support); verify and expand with real facts.
PROMPT_VARS: dict[str, str] = {'byline_service_sentence': 'TC Roofing & Restorations serves homeowners across the Dallas-Fort Worth '
                            'Metroplex.',
 'claims_assistance_phrase': 'insurance claim support',
 'company_name': 'TC Roofing & Restorations',
 'company_profile_block': 'COMPANY PROFILE — weave these facts naturally into the post where the topic '
                          'fits:\n'
                          '- **Name:** TC Roofing & Restorations — GAF Master Elite–certified roofing '
                          'contractor serving the Dallas-Fort Worth Metroplex since 2018\n'
                          '- **Services:** professional roof inspection, AI drone inspection, roof repair '
                          'and replacement, storm damage restoration, hail damage repair, insurance claim '
                          'support\n'
                          '\n'
                          'WHEN TO MENTION TC ROOFING IN THE BODY (1–2 sentences per touchpoint, varied '
                          'phrasing each time):\n'
                          '- **Inspection sections** → reference the AI drone inspection and the dated '
                          'photographs and line-item estimate it produces\n'
                          '- **Materials / replacement sections** → reference GAF Master Elite certification '
                          'and enhanced manufacturer warranties\n'
                          "- **Insurance / claims sections** → reference TC Roofing's insurance claim "
                          'support\n'
                          '\n'
                          'Do NOT use the exact phrase "Contact TC Roofing & Restorations for a free '
                          'inspection." in these mid-body mentions — reserve that phrase for the single '
                          'closing CTA only.\n'
                          '\n'
                          'KEYWORD TARGETS — use these naturally; do not repeat or force them:\n'
                          '- "professional roof inspection" or "roof inspection" — at least twice in the '
                          'post\n'
                          '- "AI drone inspection" — at least once when inspection is discussed\n'
                          '- "storm damage restoration" — when the story angle involves storm damage\n'
                          '- "hail damage repair" — when the angle covers hail\n'
                          '- "roof replacement" or "roof repair" — at least twice\n'
                          '- "insurance claim support" — when the angle covers claims or coverage\n'
                          '- "GAF Master Elite" or "GAF-certified" — at least once when discussing materials '
                          'or contractor selection',
 'company_short': 'TC Roofing',
 'contractor_perspective_name': 'TC Roofing',
 'county_guides_counties': 'Tarrant, Dallas County, Collin, Denton, and Rockwall',
 'cta_sentence': 'Contact TC Roofing & Restorations for a free inspection.',
 'drone_inspection_phrase': 'AI drone inspection',
 'drone_inspection_phrase_plural': 'AI drone inspections',
 'example_county_a': 'Tarrant County',
 'example_county_b': 'Collin County',
 'example_h2_older_roofs': 'What Does Hail Risk Mean for Older Roofs in Tarrant County?',
 'example_h2_risk': 'Which Tarrant County Neighborhoods Face the Highest Hail and Wind Damage Risk?',
 'example_h2_risk_scenario': 'Which Tarrant County Neighborhoods Face the Highest Hail and Wind Damage Risk?',
 'example_neighborhoods': 'Lakewood, Lake Highlands',
 'example_outlets': 'WFAA, NBC DFW, Fox 4, Dallas Morning News, NWS, Texas Legislature',
 'example_townhome_row': 'Grapevine townhomes — 1990s/2000s builds',
 'example_two_counties': 'Tarrant and Denton counties',
 'example_two_counties_industry': 'Tarrant and Collin County homeowners',
 'example_vignette_homeowner': 'McKinney homeowner',
 'example_vignette_homeowner_2': 'homeowner in McKinney',
 'example_vignette_name_city': 'Marcus in McKinney',
 'example_vignette_name_city_2': 'Denise in McKinney',
 'housing_stock_examples': '1980s–2000s suburban tract builds, brick veneer construction, DFW-area '
                           'slab-on-grade homes',
 'insurance_bill': 'HB1774',
 'insurance_cluster_key': 'tx_insurance_navigation',
 'mention_cost_services': 'storm damage restoration or insurance claim support',
 'mention_example_certification': '(e.g., "As a GAF Master Elite–certified contractor, TC Roofing & '
                                  'Restorations carries enhanced manufacturer warranties unavailable from '
                                  'uncertified installers.")',
 'mention_example_inspection': '(e.g., "TC Roofing & Restorations uses AI drone inspection to document hail '
                               'impact patterns and granule loss across the full roof surface before a claim '
                               'is filed.")',
 'metro_area': 'Dallas-Fort Worth',
 'metro_city': 'Dallas-Fort Worth',
 'out_of_state_bill_examples': '"California Senate passes...", "Colorado Governor signs...", "Florida '
                               'insurance reform..."',
 'out_of_state_examples_audit': 'Michigan, Georgia, California',
 'out_of_state_examples_events': 'Colorado insurance law, California wildfire policy, Florida hurricane '
                                 'response',
 'out_of_state_examples_paren': 'Colorado, California, New York, Florida',
 'out_of_state_list_a': 'California, Colorado, Florida, New York, or any other non-Texas state',
 'out_of_state_list_b': 'California, Colorado, Florida, or any other non-Texas state',
 'state': 'Texas',
 'storm_season_anchor_phrase': "DFW's spring hail season (March–June) and fall severe weather peak",
 'storm_season_phrase': "DFW's spring hail season (March–June) and fall severe weather peak",
 'us_region_phrase': 'the South Central or Sun Belt'}

# --- Strategy cluster keys ---
INSURANCE_CLUSTER_KEY = "tx_insurance_navigation"

# --- Search (pipeline/search.py) ---
SEARCH_TRADE_STAGE_NAME = "dfw_roofing_trade_21_day"

SEARCH_PRIORITY_SOURCES = ['wfaa.com',
 'nbcdfw.com',
 'fox4news.com',
 'dallasnews.com',
 'star-telegram.com',
 'cbsdfw.com',
 'weather.gov',
 'legis.state.tx.us',
 'tdi.texas.gov',
 'wbap.com',
 'kera.org',
 'communityimpact.com',
 'patch.com']

SEARCH_SECONDARY_SOURCES = ['planomagazine.com',
 'starlocalmedia.com',
 'allenamerican.com',
 'mckinneycourier-gazette.com',
 'frisco-enterprise.com',
 'prospertribune.com',
 'wylieonline.com',
 'rockwallcountynews.com',
 'rowlettrecord.com',
 'mansfield-news-mirror.com',
 'arlingtonnow.com',
 'irvingnow.com',
 'weatherforddemocrat.com',
 'dentonrc.com',
 'dallasobserver.com',
 'dmagazine.com',
 'waxahachietx.com',
 'corsicanadailysun.com',
 'ntdaily.com']

SEARCH_OFFICIAL_SOURCES = ['weather.gov',
 'legis.state.tx.us',
 'tdi.texas.gov',
 'dallascounty.org',
 'tarrantcounty.com',
 'collincountytx.gov',
 'dentoncounty.gov',
 'rockwallcountytexas.com',
 'fortworthtexas.gov',
 'dallascityhall.com',
 'fema.gov',
 'nws.noaa.gov',
 'spc.noaa.gov',
 'ready.gov',
 'texasattorneygeneral.gov',
 'icc-es.org']

SEARCH_ROOFING_TRADE_SOURCES = ['insurancejournal.com',
 'dallasnews.com',
 'star-telegram.com',
 'wfaa.com',
 'fox4news.com',
 'nbcdfw.com',
 'tdi.texas.gov',
 'roughnotes.com',
 'propertycasualty360.com',
 'dentonrc.com',
 'starlocalmedia.com',
 'communityimpact.com']

SEARCH_STRATEGY_CLUSTERS = {'storm_damage': {'pillar_topic': 'Dallas-Fort Worth storm damage inspection and repair',
                  'trigger_window_hours': 72,
                  'queries': ['Dallas hail roof damage',
                              'Fort Worth tornado roof damage',
                              'Tarrant County wind roof damage',
                              'Collin County hail roof damage',
                              'North Texas severe weather roof',
                              'DFW tree fall roof damage',
                              'Denton County hail shingle damage',
                              'Plano hail roof replacement',
                              'Dallas flash flood roof leak',
                              'Texas straight line wind roof',
                              'DFW storm roof inspection',
                              'Rockwall County tornado roof',
                              'McKinney microburst roof damage']},
 'tx_insurance_navigation': {'pillar_topic': 'Texas roof insurance claims, RCV vs ACV, HB1774',
                             'trigger_window_hours': 48,
                             'queries': ['Texas roof insurance claim',
                                         'Dallas RCV ACV roof claim',
                                         'Texas HB1774 hail deductible',
                                         'DFW roof insurance nonrenewal',
                                         'Texas roof depreciation claim',
                                         'Dallas insurance adjuster roof inspection',
                                         'Texas roof claim supplement',
                                         'Tarrant County roof insurance dispute',
                                         'Collin County homeowners insurance roof age',
                                         'Texas actual cash value roof',
                                         'DFW roof insurance endorsement',
                                         'Texas Department of Insurance roof claim',
                                         'Dallas County hail insurance claim',
                                         'Texas catastrophe hail roof deductible']},
 'roof_safety': {'pillar_topic': 'Dallas-Fort Worth roof safety, fires, penetrations, '
                                 'structural risk',
                 'trigger_window_hours': 48,
                 'queries': ['Dallas roof fire damage',
                             'Tarrant County chimney roof fire',
                             'Fort Worth unsafe structure roof',
                             'Collin County pipe boot roof leak',
                             'Dallas attic mold roof ventilation',
                             'Dallas County building code roof inspection',
                             'Texas roof collapse structural',
                             'Fort Worth HVAC roof penetration fire',
                             'DFW flat roof ponding',
                             'Denton County ice storm roof damage',
                             'Dallas solar panel roof leak',
                             'Tarrant County roof structural inspection',
                             'DFW flashing failure roof leak',
                             'Texas roof ventilation fire safety',
                             'Rockwall roof water intrusion damage']},
 'county_guides': {'pillar_topic': 'County-specific roof guidance for Dallas-Fort Worth',
                   'trigger_window_hours': None,
                   'queries': ['Dallas County roof permit',
                               'Tarrant County roof storm damage',
                               'Collin County hail roof damage',
                               'Denton County roof permit',
                               'Rockwall County storm roof repair',
                               'Dallas County roof insurance claim',
                               'Tarrant County hail roof damage',
                               'Collin County roof permit storm',
                               'Denton County roof replacement hail',
                               'Fort Worth roof code inspection',
                               'Dallas roof permit requirements',
                               'Tarrant County roof storm insurance',
                               'Collin County unsafe structure roof',
                               'Denton County roof building permit',
                               'McKinney hail roof insurance',
                               'Plano roof permit requirements']}}

SEARCH_LOCAL_TERMS = ['dallas',
 'fort worth',
 'dfw',
 'dallas-fort worth',
 'north texas',
 'texas',
 'tarrant',
 'tarrant county',
 'collin',
 'collin county',
 'denton',
 'denton county',
 'dallas county',
 'rockwall',
 'rockwall county',
 'plano',
 'frisco',
 'mckinney',
 'allen',
 'arlington',
 'irving',
 'garland',
 'carrollton',
 'lewisville',
 'grand prairie',
 'mesquite',
 'keller',
 'flower mound',
 'southlake',
 'grapevine',
 'wylie',
 'rowlett',
 'richardson',
 'mansfield',
 'euless',
 'bedford',
 'hurst',
 'anna',
 'little elm',
 'prosper',
 'celina',
 'fate',
 'heath',
 'murphy',
 'sachse',
 'desoto',
 'cedar hill',
 'duncanville',
 'lancaster',
 'burleson',
 'benbrook',
 'north richland hills',
 'haltom city',
 'saginaw',
 'azle',
 'weatherford',
 'waxahachie']

SEARCH_STATE_LOCAL_TERMS = ['texas', 'north texas']

SEARCH_TOPIC_TERMS = ['roof',
 'roofing',
 'shingle',
 'gutter',
 'siding',
 'exterior',
 'storm',
 'hail',
 'wind',
 'thunderstorm',
 'tornado',
 'weather',
 'insurance',
 'claim',
 'building code',
 'hoa',
 'fire',
 'damage',
 'flooding',
 'permit',
 'inspection',
 'unsafe',
 'safety',
 'structural',
 'construction',
 'hvac',
 'pipe boot',
 'flashing',
 'attic',
 'ventilation',
 'deductible',
 'rcv',
 'acv',
 'hb1774',
 'house bill 1774',
 'architectural shingle',
 'asphalt shingle',
 'metal roof',
 'flat roof',
 'tpo',
 'epdm',
 'modified bitumen',
 'slate roof',
 'tile roof',
 'ridge cap',
 'ridge vent',
 'soffit',
 'fascia',
 'drip edge',
 'ice barrier',
 'underlayment',
 'felt paper',
 'synthetic underlayment',
 'decking',
 'roof deck',
 'plywood decking',
 'osb decking',
 'roof truss',
 'rafter',
 'skylight',
 'chimney flashing',
 'step flashing',
 'valley flashing',
 'pipe collar',
 'boot seal',
 'roof cement',
 'caulk',
 'sealant',
 'granule loss',
 'granule',
 'blistering',
 'curling shingle',
 'lifted shingle',
 'cracked shingle',
 'missing shingle',
 'moss',
 'algae',
 'staining',
 'ponding water',
 'ice dam',
 'gutter guard',
 'downspout',
 'soffit vent',
 'ridge ventilation',
 'power attic ventilator',
 'solar attic fan',
 'roofing contractor',
 'licensed roofer',
 'roofing estimate',
 'roofing warranty',
 'manufacturer warranty',
 'workmanship warranty',
 'gaf',
 'owens corning',
 'certainteed',
 'tamko',
 'atlas roofing',
 'iko',
 'emergency tarp',
 'temporary repair',
 'supplemental claim',
 'public adjuster',
 'xactimate',
 'replacement cost',
 'actual cash value',
 'depreciation',
 'recoverable depreciation',
 'non recoverable depreciation',
 'roof age',
 'roof lifespan',
 'roof inspection report',
 'drone inspection']

SEARCH_PRIMARY_CORE_ROOFING_TERMS = ['roof',
 'roofing',
 'shingle',
 'gutter',
 'siding',
 'hail',
 'wind',
 'thunderstorm',
 'tornado',
 'flashing',
 'attic',
 'underlayment',
 'roofer',
 'roofing contractor',
 'emergency tarp',
 'architectural shingle',
 'metal roof',
 'flat roof',
 'pipe boot',
 'ridge cap',
 'soffit',
 'fascia',
 'granule loss',
 'missing shingle',
 'roof leak',
 'ice dam',
 'roof collapse',
 'roof inspection report',
 'drone inspection',
 'building permit',
 'hb1774',
 'house bill 1774',
 'contractor',
 'restoration',
 'roof restoration',
 'milestone']

SEARCH_OUT_OF_MARKET_STATE_TERMS = ['colorado',
 'georgia',
 'atlanta',
 'florida',
 'california',
 'arizona',
 'ohio',
 'alabama',
 'tennessee',
 'louisiana',
 'new york',
 'pennsylvania',
 'michigan',
 'illinois',
 'virginia',
 'maryland',
 'north carolina',
 'south carolina',
 'kentucky',
 'mississippi',
 'arkansas',
 'missouri',
 'indiana',
 'wisconsin',
 'minnesota',
 'iowa',
 'nebraska',
 'kansas',
 'utah',
 'nevada',
 'oregon',
 'washington state',
 'new mexico',
 'connecticut',
 'massachusetts',
 'new jersey',
 'denver',
 'centennial, co',
 'boulder',
 'phoenix',
 'miami',
 'orlando']

SEARCH_METRO_NEWS_DOMAIN_EXCLUSIONS = {'legis.state.tx.us', 'weather.gov', 'tdi.texas.gov'}

SEARCH_STATE_SCOPED_DOMAIN_MARKERS = ('.tx.gov',
 'tdi.texas.gov',
 'legis.state.tx.us',
 'wfaa.com',
 'dallascounty.org',
 'tarrantcounty.com',
 'nbcdfw.com',
 'fortworthtexas.gov',
 'dallascityhall.com')

SEARCH_CLUSTER_TERMS = {'storm_damage': ['roof',
                  'storm',
                  'hail',
                  'wind',
                  'thunderstorm',
                  'tornado',
                  'weather',
                  'insurance',
                  'claim',
                  'missing shingle',
                  'lifted shingle',
                  'granule loss',
                  'tree branch',
                  'emergency tarp',
                  'temporary repair',
                  'roof leak',
                  'water intrusion',
                  'ice dam',
                  'ponding water',
                  'derecho',
                  'microburst',
                  'straight line wind'],
 'tx_insurance_navigation': ['roof',
                             'insurance',
                             'claim',
                             'deductible',
                             'rcv',
                             'acv',
                             'hb1774',
                             'house bill 1774',
                             'policy',
                             'replacement cost',
                             'actual cash value',
                             'depreciation',
                             'recoverable depreciation',
                             'supplemental claim',
                             'public adjuster',
                             'xactimate',
                             'roof age',
                             'nonrenewal',
                             'endorsement',
                             'exclusion',
                             'catastrophe savings account',
                             'underpaid claim',
                             'tdi',
                             'texas department of insurance'],
 'roof_safety': ['roof',
                 'fire',
                 'safety',
                 'structural',
                 'construction',
                 'inspection',
                 'hvac',
                 'attic',
                 'ventilation',
                 'flashing',
                 'pipe boot',
                 'boot seal',
                 'chimney flashing',
                 'step flashing',
                 'granule loss',
                 'moss',
                 'algae',
                 'mold',
                 'moisture',
                 'rot',
                 'roof collapse',
                 'structural failure',
                 'solar panel',
                 'flat roof',
                 'ponding water',
                 'ice dam',
                 'power attic ventilator'],
 'county_guides': ['roof',
                   'permit',
                   'storm',
                   'hail',
                   'wind',
                   'insurance',
                   'replacement',
                   'repair',
                   'building permit',
                   'residential permit',
                   'permit requirements',
                   'unsafe structure',
                   'code violation',
                   'hoa requirement',
                   'county ordinance',
                   'inspection required',
                   'licensed contractor required']}

# --- Evaluate (pipeline/evaluate.py) ---
# 'generic' is filled with str.format(title=...).
EVALUATE_FALLBACK_ANGLES = {'storm': 'What should Dallas-Fort Worth homeowners inspect after this storm or damage report?',
 'insurance': 'How does this Texas insurance update affect roof repair or replacement claims?',
 'safety': 'What roof safety risks should DFW homeowners understand from this local report?',
 'generic': 'What should Dallas-Fort Worth homeowners know about {title}?'}
